QTags.addButton( 'ilinks', '链接按钮', "[dm href='']", "[/dm]" );
QTags.addButton( 'idownload', '下载按钮', "[dl href='']", "[/dl]" );
QTags.addButton( 'ikaiyuan', '开源按钮', "[gt href='']开源地址[/gt]", "" );
QTags.addButton( 'v_notice', '绿色通知', "[v_notice]", "[/v_notice]" );
QTags.addButton( 'v_error', '红色警告', "[v_error]", "[/v_error]" );
QTags.addButton( 'v_warn', '黄色错误', "[v_warn]", "[/v_warn]" );
QTags.addButton( 'v_tips', '灰色提示', "[v_tips]", "[/v_tips]" );
QTags.addButton( 'v_blue', '蓝色提示', "[v_blue]", "[/v_blue]" );
QTags.addButton( 'v_act', '蓝边文本', "[v_act]", "[/v_act]" );
QTags.addButton( 'v_organge', '橙色文本', "[v_organge]", "[/v_organge]" );
QTags.addButton( 'v_qing', '青色文本', "[v_qing]", "[/v_qing]" );
QTags.addButton( 'v_pink', '粉色文本', "[v_pink]", "[/v_pink]" );
QTags.addButton( 'music', '音乐按钮', "[music]", "[/music]" );
QTags.addButton( 'video', '视频按钮', "[video]", "[/video]" );
QTags.addButton( 'reply', '回复可见', "[reply]", "[/reply]" );
QTags.addButton( 'buy', '购买商品可见', '[buy product_id="产品ID"]购买产品才能查看的内容[/buy]' );
QTags.addButton( 'collapse', '隐藏收缩', '[collapse title=""]', '[/collapse]' );
QTags.addButton( 'dltable', '下载面板', '[dltable file="在此处写下文件名称" size="在这里写下文件大小"]这里留文件下载A标签链接，可以放多个链接[/dltable]' );